version: 2.1

parameters:
  slack-mentions:
    type: string
    default: 'S01JP5A3ACQ'
  only_for_branches:
    type: string
    default: 'main'

orbs:
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.1.0

executors:
  terraform12:
    docker:
      - image: techallylw/terraform:12
  terraform13:
    docker:
      - image: techallylw/terraform:13
  alpine:
    docker:
      - image: cibuilds/base:latest
    resource_class: small

jobs:
  terraform12-test:
    executor: terraform12
    steps:
      - checkout
      - run: scripts/ci_tests.sh
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  terraform13-test:
    executor: terraform13
    steps:
      - checkout
      - run: scripts/ci_tests.sh
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  verify-release:
    executor: alpine
    steps:
      - checkout
      - run: scripts/release.sh verify
  trigger-release:
    executor: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:a1:b6:ec:f2:2f:2a:d1:18:e7:d6:78:d6:2d:a6:a5"
      - run: scripts/release.sh trigger
  release:
    executor: alpine
    steps:
      - checkout
      - jq/install
      - slack/notify:
          mentions: << pipeline.parameters.slack-mentions >>
          message: Releasing new version of this repository
      - run: scripts/release.sh publish
      - slack/status:
          mentions: << pipeline.parameters.slack-mentions >>

workflows:
  version: 2
  test-trigger-release:
    jobs:
      - terraform12-test:
          context:
            - techally_api_key
      - terraform13-test:
          context:
            - techally_api_key
      - trigger-release:
          requires:
            - terraform12-test
            - terraform13-test
          filters:
            branches:
              only: main

  verify-release:
    jobs:
      - verify-release:
          filters:
             branches:
               only: release

  release-from-tag:
    jobs:
      - release:
          filters:
            tags:
               only: /^v.*/
            branches:
              ignore: /.*/
          context:
            - techally_releases

  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: main
    jobs:
      - terraform12-test:
          context:
            - techally_api_key
      - terraform13-test:
          context:
            - techally_api_key
