name: Nightly Build

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # Run every day at 10AM UTC

jobs:
  call-nightly-workflow:
    uses: lacework/oss-actions/.github/workflows/tf-nightly.yml@main
    secrets: inherit
