name: Test Compatibility

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  
jobs:
  call-test-compat:
    uses: lacework/oss-actions/.github/workflows/tf-test-compatibility.yml@main
    secrets: inherit
