name: Verify Release

on: 
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  call-nightly-workflow:
    uses: lacework/oss-actions/.github/workflows/tf-verify.yml@main
    secrets: inherit
